// Catálogo de plantas: recomendaciones de cultivo y combinaciones (asociación de cultivos).
// Cada planta tiene un id estable usado para relaciones de compañerismo.
const PLANT_CATALOG = [
  { id: "tomate", nombre: "Tomate", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular y profundo, 2-3 veces por semana. Evitar mojar el follaje para prevenir hongos.",
    fertilizante: "Rico en fósforo y potasio al florecer. Compost al trasplantar, refuerzo cada 3-4 semanas.",
    espaciado: "40-50 cm entre plantas.", diasGerminacion: "6-14 días", diasCosecha: "60-85 días desde trasplante",
    heladaSensible: true,
    buenos: ["albahaca", "zanahoria", "perejil", "cebolla", "caléndula", "espinaca"],
    malos: ["maiz", "papa", "hinojo", "repollo"],
    notas: "Entutorar para mejor aireación. Muy sensible a heladas." },
  { id: "pimiento", nombre: "Pimiento / Morrón", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego constante, suelo húmedo pero sin encharcar.",
    fertilizante: "Compost al plantar, refuerzo con potasio en floración.",
    espaciado: "35-45 cm entre plantas.", diasGerminacion: "10-21 días", diasCosecha: "60-90 días desde trasplante",
    heladaSensible: true,
    buenos: ["albahaca", "cebolla", "zanahoria", "caléndula"],
    malos: ["hinojo", "poroto"],
    notas: "Prefiere calor estable, ideal para el Chaco en primavera-verano." },
  { id: "berenjena", nombre: "Berenjena", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular, no dejar secar el suelo por completo.",
    fertilizante: "Compost rico al plantar, refuerzo mensual.",
    espaciado: "45-60 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "70-90 días desde trasplante",
    heladaSensible: true,
    buenos: ["poroto", "albahaca"],
    malos: [],
    notas: "Muy sensible al frío, no trasplantar hasta que no haya riesgo de helada." },
  { id: "lechuga", nombre: "Lechuga", categoria: "hortaliza", sol: "semisombra", agua: "medio",
    riego: "Riego frecuente y liviano, mantener el suelo siempre húmedo.",
    fertilizante: "Compost liviano al plantar, nitrógeno moderado.",
    espaciado: "20-30 cm entre plantas.", diasGerminacion: "3-10 días", diasCosecha: "45-60 días",
    heladaSensible: false,
    buenos: ["zanahoria", "rabanito", "cebolla", "fresa"],
    malos: ["perejil"],
    notas: "Tolera frío leve, mejor en meses más frescos del año." },
  { id: "zanahoria", nombre: "Zanahoria", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego constante y uniforme para evitar raíces deformes.",
    fertilizante: "Evitar exceso de nitrógeno; suelo suelto y bien drenado.",
    espaciado: "5-8 cm entre plantas.", diasGerminacion: "14-21 días", diasCosecha: "70-80 días",
    heladaSensible: false,
    buenos: ["tomate", "lechuga", "cebolla", "arveja"],
    malos: ["eneldo"],
    notas: "Suelo profundo y sin piedras para raíces derechas." },
  { id: "cebolla", nombre: "Cebolla", categoria: "hortaliza", sol: "pleno", agua: "bajo",
    riego: "Riego moderado, reducir hacia la cosecha.",
    fertilizante: "Compost al plantar, poco nitrógeno adicional.",
    espaciado: "10-15 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "90-120 días",
    heladaSensible: false,
    buenos: ["tomate", "zanahoria", "lechuga", "pimiento"],
    malos: ["poroto", "arveja"],
    notas: "Buen repelente natural de plagas para varios cultivos." },
  { id: "ajo", nombre: "Ajo", categoria: "hortaliza", sol: "pleno", agua: "bajo",
    riego: "Riego moderado, suspender semanas antes de cosechar.",
    fertilizante: "Compost al plantar, fósforo moderado.",
    espaciado: "10-15 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "150-210 días",
    heladaSensible: false,
    buenos: ["tomate", "zanahoria", "fresa"],
    malos: ["poroto", "arveja"],
    notas: "Ciclo largo, tolera bien el frío del invierno chaqueño." },
  { id: "calabacin", nombre: "Calabacín / Zapallito", categoria: "hortaliza", sol: "pleno", agua: "alto",
    riego: "Riego abundante y regular, sobre todo en floración.",
    fertilizante: "Compost rico, refuerzo con potasio en fructificación.",
    espaciado: "60-90 cm entre plantas.", diasGerminacion: "5-10 días", diasCosecha: "45-55 días",
    heladaSensible: true,
    buenos: ["maiz", "caléndula"],
    malos: ["papa"],
    notas: "Necesita polinizadores; plantar flores cercanas ayuda." },
  { id: "calabaza", nombre: "Calabaza / Zapallo", categoria: "hortaliza", sol: "pleno", agua: "alto",
    riego: "Riego profundo y regular.",
    fertilizante: "Compost rico al plantar.",
    espaciado: "90-120 cm entre plantas.", diasGerminacion: "5-10 días", diasCosecha: "80-110 días",
    heladaSensible: true,
    buenos: ["maiz", "poroto"],
    malos: ["papa"],
    notas: "Requiere mucho espacio; ideal en cama de cultivo en el suelo." },
  { id: "sandia", nombre: "Sandía", categoria: "fruta", sol: "pleno", agua: "alto",
    riego: "Riego profundo, reducir cerca de la cosecha para concentrar dulzor.",
    fertilizante: "Compost rico, potasio en fructificación.",
    espaciado: "90-180 cm entre plantas.", diasGerminacion: "7-10 días", diasCosecha: "80-100 días",
    heladaSensible: true,
    buenos: ["maiz"],
    malos: ["papa"],
    notas: "Muy adaptada al calor del Chaco en verano." },
  { id: "melon", nombre: "Melón", categoria: "fruta", sol: "pleno", agua: "alto",
    riego: "Riego regular, reducir antes de cosechar.",
    fertilizante: "Compost rico, potasio en floración.",
    espaciado: "60-90 cm entre plantas.", diasGerminacion: "5-10 días", diasCosecha: "70-90 días",
    heladaSensible: true,
    buenos: ["maiz"],
    malos: ["papa"],
    notas: "Muy sensible al frío nocturno." },
  { id: "maiz", nombre: "Maíz", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular, crítico durante la floración.",
    fertilizante: "Alto en nitrógeno, refuerzo cuando la planta tiene rodilla alta.",
    espaciado: "25-30 cm entre plantas.", diasGerminacion: "6-10 días", diasCosecha: "70-100 días",
    heladaSensible: true,
    buenos: ["poroto", "calabaza", "sandia", "melon"],
    malos: ["tomate"],
    notas: "La combinación maíz-poroto-zapallo (las tres hermanas) funciona muy bien." },
  { id: "poroto", nombre: "Poroto / Frijol", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego moderado, evitar encharcar.",
    fertilizante: "Poco nitrógeno (fija el suyo propio), compost liviano.",
    espaciado: "10-15 cm entre plantas.", diasGerminacion: "6-10 días", diasCosecha: "50-65 días",
    heladaSensible: true,
    buenos: ["maiz", "calabaza", "pepino", "berenjena"],
    malos: ["cebolla", "ajo"],
    notas: "Fija nitrógeno en el suelo, buen antecesor para hojas verdes." },
  { id: "arveja", nombre: "Arveja", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego moderado y constante.",
    fertilizante: "Poco nitrógeno adicional, fósforo moderado.",
    espaciado: "5-10 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "60-70 días",
    heladaSensible: false,
    buenos: ["zanahoria", "rabanito"],
    malos: ["cebolla", "ajo"],
    notas: "Tolera bien el fresco de invierno en el Chaco." },
  { id: "rucula", nombre: "Rúcula", categoria: "hortaliza", sol: "semisombra", agua: "medio",
    riego: "Riego frecuente y liviano.",
    fertilizante: "Compost liviano, nitrógeno moderado.",
    espaciado: "10-15 cm entre plantas.", diasGerminacion: "3-7 días", diasCosecha: "30-40 días",
    heladaSensible: false,
    buenos: ["zanahoria", "remolacha"],
    malos: [],
    notas: "Ciclo muy corto, ideal para siembras escalonadas." },
  { id: "espinaca", nombre: "Espinaca", categoria: "hortaliza", sol: "semisombra", agua: "medio",
    riego: "Riego regular, suelo siempre húmedo.",
    fertilizante: "Compost rico en nitrógeno.",
    espaciado: "15-20 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "40-50 días",
    heladaSensible: false,
    buenos: ["tomate", "fresa"],
    malos: [],
    notas: "Prefiere temperaturas frescas, sembrar en otoño-invierno." },
  { id: "acelga", nombre: "Acelga", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular.",
    fertilizante: "Compost al plantar, nitrógeno moderado.",
    espaciado: "20-30 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "50-60 días",
    heladaSensible: false,
    buenos: ["cebolla", "rabanito"],
    malos: [],
    notas: "Muy resistente, cosecha continua cortando hojas externas." },
  { id: "remolacha", nombre: "Remolacha", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego constante para raíces parejas.",
    fertilizante: "Compost moderado, evitar exceso de nitrógeno.",
    espaciado: "10-15 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "55-70 días",
    heladaSensible: false,
    buenos: ["cebolla", "rucula"],
    malos: ["poroto"],
    notas: "Suelo suelto y profundo para buen desarrollo de raíz." },
  { id: "rabanito", nombre: "Rabanito", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular y constante.",
    fertilizante: "Compost liviano, poco nitrógeno.",
    espaciado: "5 cm entre plantas.", diasGerminacion: "3-7 días", diasCosecha: "25-35 días",
    heladaSensible: false,
    buenos: ["lechuga", "arveja", "zanahoria"],
    malos: [],
    notas: "Muy rápido, ideal para intercalar entre plantas de ciclo largo." },
  { id: "pepino", nombre: "Pepino", categoria: "hortaliza", sol: "pleno", agua: "alto",
    riego: "Riego abundante y regular.",
    fertilizante: "Compost rico, potasio en floración.",
    espaciado: "40-60 cm entre plantas.", diasGerminacion: "5-10 días", diasCosecha: "50-70 días",
    heladaSensible: true,
    buenos: ["poroto", "maiz"],
    malos: ["papa"],
    notas: "Se beneficia de tutorado vertical para ahorrar espacio." },
  { id: "papa", nombre: "Papa", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular, reducir antes de cosechar.",
    fertilizante: "Compost al plantar, potasio moderado.",
    espaciado: "30-40 cm entre plantas.", diasGerminacion: "14-21 días", diasCosecha: "90-120 días",
    heladaSensible: true,
    buenos: ["maiz"],
    malos: ["tomate", "calabaza", "pepino", "girasol"],
    notas: "Aporcar la tierra a medida que crece." },
  { id: "repollo", nombre: "Repollo", categoria: "hortaliza", sol: "pleno", agua: "medio",
    riego: "Riego regular y constante.",
    fertilizante: "Compost rico en nitrógeno.",
    espaciado: "40-50 cm entre plantas.", diasGerminacion: "7-12 días", diasCosecha: "70-100 días",
    heladaSensible: false,
    buenos: ["cebolla", "remolacha"],
    malos: ["tomate", "fresa"],
    notas: "Prefiere clima fresco, mejor otoño-invierno en el Chaco." },
  { id: "albahaca", nombre: "Albahaca", categoria: "hierba", sol: "pleno", agua: "medio",
    riego: "Riego regular, no dejar secar por completo.",
    fertilizante: "Compost liviano, sin exceso de nitrógeno.",
    espaciado: "20-25 cm entre plantas.", diasGerminacion: "5-10 días", diasCosecha: "60-70 días",
    heladaSensible: true,
    buenos: ["tomate", "pimiento"],
    malos: [],
    notas: "Repele algunos insectos, excelente compañera del tomate." },
  { id: "perejil", nombre: "Perejil", categoria: "hierba", sol: "semisombra", agua: "medio",
    riego: "Riego regular.",
    fertilizante: "Compost liviano.",
    espaciado: "15-20 cm entre plantas.", diasGerminacion: "14-28 días", diasCosecha: "70-90 días",
    heladaSensible: false,
    buenos: ["tomate"],
    malos: ["lechuga"],
    notas: "Germinación lenta, tener paciencia." },
  { id: "cilantro", nombre: "Cilantro", categoria: "hierba", sol: "semisombra", agua: "medio",
    riego: "Riego regular y liviano.",
    fertilizante: "Compost liviano.",
    espaciado: "15-20 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "40-50 días",
    heladaSensible: false,
    buenos: ["espinaca"],
    malos: ["hinojo"],
    notas: "Se va a flor rápido con calor; sembrar en tandas." },
  { id: "romero", nombre: "Romero", categoria: "hierba", sol: "pleno", agua: "bajo",
    riego: "Riego escaso, tolera bien la sequía una vez establecido.",
    fertilizante: "Mínimo, suelo bien drenado.",
    espaciado: "40-60 cm entre plantas.", diasGerminacion: "15-25 días", diasCosecha: "12-18 meses hasta planta madura",
    heladaSensible: false,
    buenos: ["repollo", "zanahoria"],
    malos: [],
    notas: "Perenne, ideal en bordes del bancal." },
  { id: "hinojo", nombre: "Hinojo", categoria: "hierba", sol: "pleno", agua: "medio",
    riego: "Riego regular.",
    fertilizante: "Compost moderado.",
    espaciado: "30-40 cm entre plantas.", diasGerminacion: "10-14 días", diasCosecha: "90-115 días",
    heladaSensible: false,
    buenos: [],
    malos: ["tomate", "pimiento", "cilantro"],
    notas: "Inhibe a muchas otras plantas; cultivar aislado." },
  { id: "eneldo", nombre: "Eneldo", categoria: "hierba", sol: "pleno", agua: "medio",
    riego: "Riego regular.",
    fertilizante: "Compost liviano.",
    espaciado: "20-30 cm entre plantas.", diasGerminacion: "10-14 días", diasCosecha: "40-60 días",
    heladaSensible: false,
    buenos: ["repollo"],
    malos: ["zanahoria"],
    notas: "Atrae insectos benéficos como avispas parasitoides." },
  { id: "fresa", nombre: "Fresa / Frutilla", categoria: "fruta", sol: "pleno", agua: "medio",
    riego: "Riego regular, evitar mojar los frutos.",
    fertilizante: "Compost al plantar, potasio en floración.",
    espaciado: "25-30 cm entre plantas.", diasGerminacion: "-", diasCosecha: "90-110 días desde plantín",
    heladaSensible: true,
    buenos: ["lechuga", "espinaca", "ajo"],
    malos: ["repollo"],
    notas: "Casi siempre se planta como plantín, no por semilla." },
  { id: "limonero", nombre: "Limonero", categoria: "fruta", sol: "pleno", agua: "medio",
    riego: "Riego profundo y espaciado, sin encharcar raíces.",
    fertilizante: "Cítricos: rico en nitrógeno, refuerzo cada 2-3 meses en crecimiento.",
    espaciado: "3-4 m entre plantas.", diasGerminacion: "-", diasCosecha: "2-3 años hasta primera cosecha",
    heladaSensible: true,
    buenos: [],
    malos: [],
    notas: "Proteger tronco joven en heladas fuertes del Chaco." },
  { id: "naranjo", nombre: "Naranjo", categoria: "fruta", sol: "pleno", agua: "medio",
    riego: "Riego profundo y espaciado.",
    fertilizante: "Cítricos: rico en nitrógeno, refuerzo estacional.",
    espaciado: "3-5 m entre plantas.", diasGerminacion: "-", diasCosecha: "2-3 años hasta primera cosecha",
    heladaSensible: true,
    buenos: [],
    malos: [],
    notas: "Sensible cuando joven, proteger en noches de helada." },
  { id: "girasol", nombre: "Girasol", categoria: "flor", sol: "pleno", agua: "medio",
    riego: "Riego regular, más en floración.",
    fertilizante: "Compost moderado, fósforo para floración.",
    espaciado: "30-60 cm entre plantas.", diasGerminacion: "7-14 días", diasCosecha: "70-90 días a floración",
    heladaSensible: true,
    buenos: ["maiz"],
    malos: ["papa"],
    notas: "Atrae polinizadores; puede dar sombra a cultivos bajos." },
  { id: "caléndula", nombre: "Caléndula", categoria: "flor", sol: "pleno", agua: "bajo",
    riego: "Riego moderado.",
    fertilizante: "Mínimo, suelo bien drenado.",
    espaciado: "20-30 cm entre plantas.", diasGerminacion: "5-10 días", diasCosecha: "50-60 días a floración",
    heladaSensible: false,
    buenos: ["tomate", "pimiento", "calabacin"],
    malos: [],
    notas: "Repele nematodos y atrae insectos benéficos." },
  { id: "petunia", nombre: "Petunia", categoria: "flor", sol: "pleno", agua: "medio",
    riego: "Riego regular, no encharcar.",
    fertilizante: "Compost liviano, floración prolongada con refuerzo mensual.",
    espaciado: "20-30 cm entre plantas.", diasGerminacion: "10-14 días", diasCosecha: "60-70 días a floración",
    heladaSensible: true,
    buenos: [],
    malos: [],
    notas: "Buena opción decorativa en bordes de bancales." },
  { id: "rosa", nombre: "Rosa", categoria: "flor", sol: "pleno", agua: "medio",
    riego: "Riego profundo, evitar mojar el follaje.",
    fertilizante: "Compost rico, refuerzo cada 4-6 semanas en floración.",
    espaciado: "50-100 cm entre plantas.", diasGerminacion: "-", diasCosecha: "-",
    heladaSensible: false,
    buenos: ["ajo", "caléndula"],
    malos: [],
    notas: "Casi siempre se planta como plantín injertado." }
];

// Devuelve info de catálogo por id
function getCatalogPlant(id) {
  return PLANT_CATALOG.find(p => p.id === id) || null;
}

// Evalúa relación entre dos plantas del catálogo: 'buena' | 'mala' | 'neutra'
function companionRelation(idA, idB) {
  if (idA === idB) return "neutra";
  const a = getCatalogPlant(idA), b = getCatalogPlant(idB);
  if (!a || !b) return "neutra";
  if (a.malos.includes(idB) || b.malos.includes(idA)) return "mala";
  if (a.buenos.includes(idB) || b.buenos.includes(idA)) return "buena";
  return "neutra";
}
